name: Release

permissions:
  contents: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  release:
    name: GH NPM Release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: NPM pack
        run: |
          pack_file=$(npm pack)
          mv $pack_file fluvio-client-capacitor.tgz
      - name: Login GH CLI
        run: gh auth login --with-token < <(echo ${{ secrets.GITHUB_TOKEN }})
      - name: Create GH release
        run: gh release create ${{ github.event.inputs.tag }} --generate-notes
      - name: Upload NPM pack file to GH release
        run: gh release upload ${{ github.event.inputs.tag }} fluvio-client-capacitor.tgz